In [2]:
import pandas as pd
import os

In [3]:
customers_df = pd.read_csv("../data/raw/olist_customers_dataset.csv")
geolocation_df = pd.read_csv("../data/raw/olist_geolocation_dataset.csv")
order_items_df = pd.read_csv("../data/raw/olist_order_items_dataset.csv")
order_payments_df = pd.read_csv("../data/raw/olist_order_payments_dataset.csv")
order_reviews_df = pd.read_csv("../data/raw/olist_order_reviews_dataset.csv")
orders_df = pd.read_csv("../data/raw/olist_orders_dataset.csv")
products_df = pd.read_csv("../data/raw/olist_products_dataset.csv")
sellers_df = pd.read_csv("../data/raw/olist_sellers_dataset.csv")
product_category_name_translation_df = pd.read_csv("../data/raw/product_category_name_translation.csv")

In [4]:
customers_df.shape

(99441, 5)

In [5]:
os.path.getsize('../data/raw/olist_customers_dataset.csv') / 1024

8482.1357421875

In [6]:
customers_df.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [7]:
customers_df[customers_df.duplicated(subset = ['customer_id'])]

Empty DataFrame
Columns: [customer_id, customer_unique_id, customer_zip_code_prefix, customer_city, customer_state]
Index: []

In [8]:
customers_df[customers_df.duplicated(subset = ['customer_unique_id','customer_city','customer_state'], keep=False)].sort_values('customer_unique_id')

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
35608,24b0e2bd287e47d54d193e7bbb51103f,00172711b30d52eea8b313a7f2cced02,45200,jequie,BA
19299,1afe8a9c67eec3516c09a8bdcc539090,00172711b30d52eea8b313a7f2cced02,45200,jequie,BA
22066,f6efe5d5c7b85e12355f9d5c3db46da2,004288347e5e88a27ded2bb23747066c,26220,nova iguacu,RJ
20023,1b4a75b3478138e99902678254b260f4,004288347e5e88a27ded2bb23747066c,26220,nova iguacu,RJ
72451,49cf243e0d353cd418ca77868e24a670,004b45ec5c64187465168251cd1c9c2f,57055,maceio,AL
...,...,...,...,...,...
75057,1ae563fdfa500d150be6578066d83998,ff922bdd6bafcdf99cb90d7f39cea5b3,17340,barra bonita,SP
79859,d064be88116eb8b958727aec4cf56a59,ff922bdd6bafcdf99cb90d7f39cea5b3,17340,barra bonita,SP
27992,bec0bf00ac5bee64ce8ef5283051a70c,ff922bdd6bafcdf99cb90d7f39cea5b3,17340,barra bonita,SP
12133,0088395699ea0fcd459bfbef084997db,ffe254cc039740e17dd15a5305035928,37640,extrema,MG
64323,4b231c90751c27521f7ee27ed2dc3b8f,ffe254cc039740e17dd15a5305035928,37640,extrema,MG

In [9]:
customers_df.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [10]:
customers_df.dtypes

customer_id                 object
customer_unique_id          object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object

In [11]:
geolocation_df.shape

(1000163, 5)

In [12]:
os.path.getsize('../data/raw/olist_geolocation_dataset.csv') / 1024

59837.7763671875

In [13]:
geolocation_df.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [14]:
geolocation_df.duplicated().sum()

np.int64(261831)

In [15]:
geolocation_df[geolocation_df.duplicated(subset=['geolocation_zip_code_prefix', 'geolocation_state', 'geolocation_city'])]

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
2,1046,-23.546129,-46.642951,sao paulo,SP
10,1013,-23.547325,-46.634184,sao paulo,SP
15,1046,-23.546081,-46.644820,sao paulo,SP
19,1046,-23.545884,-46.643163,sao paulo,SP
20,1046,-23.545166,-46.643786,sao paulo,SP
...,...,...,...,...,...
1000158,99950,-28.068639,-52.010705,tapejara,RS
1000159,99900,-27.877125,-52.224882,getulio vargas,RS
1000160,99950,-28.071855,-52.014716,tapejara,RS
1000161,99980,-28.388932,-51.846871,david canabarro,RS
1000162,99950,-28.070104,-52.018658,tapejara,RS

In [16]:
geolocation_df[geolocation_df.duplicated(subset=['geolocation_zip_code_prefix', 'geolocation_state', 'geolocation_city', 'geolocation_lat', 'geolocation_lng'])]

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
15,1046,-23.546081,-46.644820,sao paulo,SP
44,1046,-23.546081,-46.644820,sao paulo,SP
65,1046,-23.546081,-46.644820,sao paulo,SP
66,1009,-23.546935,-46.636588,sao paulo,SP
67,1046,-23.546081,-46.644820,sao paulo,SP
...,...,...,...,...,...
1000153,99970,-28.343273,-51.873734,ciriaco,RS
1000154,99950,-28.070493,-52.011342,tapejara,RS
1000159,99900,-27.877125,-52.224882,getulio vargas,RS
1000160,99950,-28.071855,-52.014716,tapejara,RS
1000162,99950,-28.070104,-52.018658,tapejara,RS

In [110]:
geolocation_df.isna().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [121]:
geolocation_df.dtypes

geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                object
geolocation_state               object
dtype: object

In [7]:
order_items_df.shape

(112650, 7)

In [94]:
os.path.getsize('../data/raw/olist_order_items_dataset.csv') / 1024

15076.8271484375

In [87]:
order_items_df.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [115]:
order_items_df.dtypes

order_id                object
order_item_id            int64
product_id              object
seller_id               object
shipping_limit_date     object
price                  float64
freight_value          float64
dtype: object

In [125]:
order_items_df[order_items_df.duplicated(subset=['order_id', 'product_id'])].sort_values('order_id')

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
14,0008288aa423d2a3f00fcb17cd7d8719,2,368c6c730842d78016ad823897a372db,1f50f920176fa81dab994f9023523100,2018-02-21 02:55:52,49.90,13.37
33,00143d0f86d6fbd9f9b38ab440ac16f5,2,e95ee6822b66ac6058e2e4aff656071a,a17f621c590ea0fab3d5d883e1630ec6,2017-10-20 16:07:52,21.33,15.10
34,00143d0f86d6fbd9f9b38ab440ac16f5,3,e95ee6822b66ac6058e2e4aff656071a,a17f621c590ea0fab3d5d883e1630ec6,2017-10-20 16:07:52,21.33,15.10
43,001ab0a7578dd66cd4b0a71f5b6e1e41,2,0b0172eb0fd18479d29c3bc122c058c2,5656537e588803a555b8eb41f07a944b,2018-01-04 02:33:42,24.89,17.63
44,001ab0a7578dd66cd4b0a71f5b6e1e41,3,0b0172eb0fd18479d29c3bc122c058c2,5656537e588803a555b8eb41f07a944b,2018-01-04 02:33:42,24.89,17.63
...,...,...,...,...,...,...,...
112617,ffecd5a79a0084f6a592288c67e3c298,3,50fd2b788dc166edd20512370dac54df,8b321bb669392f5163d04c59e235e066,2018-03-05 20:15:27,21.90,15.79
112635,fff8287bbae429a99bb7e8c21d151c41,2,bee2e070c39f3dd2f6883a17a5f0da45,4e922959ae960d389249c378d1c939f5,2018-03-27 12:29:22,180.00,48.14
112642,fffb9224b6fc7c43ebb0904318b10b5f,3,43423cdffde7fda63d0414ed38c11a73,b1fc4f64df5a0e8b6913ab38803c57a9,2017-11-03 02:55:58,55.00,34.19
112641,fffb9224b6fc7c43ebb0904318b10b5f,2,43423cdffde7fda63d0414ed38c11a73,b1fc4f64df5a0e8b6913ab38803c57a9,2017-11-03 02:55:58,55.00,34.19
112643,fffb9224b6fc7c43ebb0904318b10b5f,4,43423cdffde7fda63d0414ed38c11a73,b1fc4f64df5a0e8b6913ab38803c57a9,2017-11-03 02:55:58,55.00,34.19

In [17]:
order_items_df[order_items_df.duplicated(subset=['order_id', 'order_item_id'])].sort_values('order_id')

Empty DataFrame
Columns: [order_id, order_item_id, product_id, seller_id, shipping_limit_date, price, freight_value]
Index: []

In [113]:
order_items_df.isna().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [119]:
pd.to_datetime(order_items_df['shipping_limit_date'])
order_items_df['shipping_limit_date'].max()

'2020-04-09 22:35:08'

In [120]:
order_items_df['shipping_limit_date'].min()

'2016-09-19 00:15:34'

In [189]:
order_items_df[['order_id', 'order_item_id']].duplicated().any()

np.False_

In [9]:
order_payments_df.shape

(103886, 5)

In [95]:
os.path.getsize('../data/raw/olist_order_payments_dataset.csv') / 1024

5641.736328125

In [49]:
order_payments_df.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [130]:
order_payments_df[order_payments_df.duplicated(subset=['order_id'])].sort_values('order_id')

,order_id,payment_sequential,payment_type,payment_installments,payment_value
89575,0016dfedd97fc2950e388d2971d718c7,1,credit_card,5,52.63
98894,002f19a65a2ddd70a090297872e6d64e,2,voucher,1,33.18
30155,0071ee2429bc1efdc43aa3e073a5290e,2,voucher,1,92.44
16053,009ac365164f8e06f59d18a08045f6c4,1,credit_card,1,0.88
32058,009ac365164f8e06f59d18a08045f6c4,4,voucher,1,5.45
...,...,...,...,...,...
26914,ff978de32e717acd3b5abe1fb069d2b6,2,voucher,1,10.80
28611,ff978de32e717acd3b5abe1fb069d2b6,3,voucher,1,0.66
55988,ffa1dd97810de91a03abd7bd76d2fed1,1,credit_card,1,36.58
32912,ffa39020fe7c8a3e907320e1bec4b985,1,credit_card,1,7.13
75188,ffc730a0615d28ec19f9cad02cb41442,1,credit_card,1,14.76

In [131]:
order_payments_df[order_payments_df.duplicated(subset=['order_id', 'payment_sequential'])].sort_values('order_id')

Empty DataFrame
Columns: [order_id, payment_sequential, payment_type, payment_installments, payment_value]
Index: []

In [127]:
order_payments_df.dtypes

order_id                 object
payment_sequential        int64
payment_type             object
payment_installments      int64
payment_value           float64
dtype: object

In [128]:
order_payments_df.isna().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [129]:
order_payments_df['payment_type'].unique()

array(['credit_card', 'boleto', 'voucher', 'debit_card', 'not_defined'],
      dtype=object)

In [191]:
order_payments_df[['order_id', 'payment_sequential']].duplicated().any()

np.False_

In [11]:
order_reviews_df.shape

(99224, 7)

In [96]:
os.path.getsize('../data/raw/olist_order_reviews_dataset.csv') / 1024

14112.958984375

In [39]:
order_reviews_df.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [21]:
order_reviews_df[order_reviews_df.duplicated(subset=['review_id', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp'],keep=False)].sort_values('review_id')

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
46678,00130cbe1f9d422698c812ed8ded1919,dfcdfc43867d1c1381bfaf62d6b9c195,1,NaN,"O cartucho ""original HP"" 60XL não é reconhecid...",2018-03-07 00:00:00,2018-03-20 18:08:23
29841,00130cbe1f9d422698c812ed8ded1919,04a28263e085d399c97ae49e0b477efa,1,NaN,"O cartucho ""original HP"" 60XL não é reconhecid...",2018-03-07 00:00:00,2018-03-20 18:08:23
90677,0115633a9c298b6a98bcbe4eee75345f,78a4201f58af3463bdab842eea4bc801,5,NaN,NaN,2017-09-21 00:00:00,2017-09-26 03:27:47
63193,0115633a9c298b6a98bcbe4eee75345f,0c9850b2c179c1ef60d2855e2751d1fa,5,NaN,NaN,2017-09-21 00:00:00,2017-09-26 03:27:47
92876,0174caf0ee5964646040cd94e15ac95e,f93a732712407c02dce5dd5088d0f47b,1,NaN,Produto entregue dentro de embalagem do fornec...,2018-03-07 00:00:00,2018-03-08 03:00:53
...,...,...,...,...,...,...,...
31120,fe5c833752953fed3209646f1f63b53c,4863e15fa53273cc7219c58f5ffda4fb,1,NaN,"Comprei dois produtos e ambos, mesmo enviados ...",2018-02-28 00:00:00,2018-02-28 13:57:52
7870,ff2fc9e68f8aabfbe18d710b83aabd30,2da58e0a7dcfa4ce1e00fad9d03ca3b5,2,NaN,NaN,2018-03-17 00:00:00,2018-03-19 11:44:15
82521,ff2fc9e68f8aabfbe18d710b83aabd30,1078d496cc6ab9a8e6f2be77abf5091b,2,NaN,NaN,2018-03-17 00:00:00,2018-03-19 11:44:15
73951,ffb8cff872a625632ac983eb1f88843c,c44883fc2529b4aa03ca90e7e09d95b6,3,NaN,NaN,2017-07-22 00:00:00,2017-07-26 13:41:07
1985,ffb8cff872a625632ac983eb1f88843c,c88b1d1b157a9999ce368f218a407141,3,NaN,NaN,2017-07-22 00:00:00,2017-07-26 13:41:07

In [132]:
order_reviews_df[order_reviews_df.duplicated(subset=['order_id'])].sort_values('order_id')

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
25612,89a02c45c340aeeb1354a24e7d4b2c1e,0035246a40f520710769010f752e7507,5,NaN,NaN,2017-08-29 00:00:00,2017-08-30 01:59:12
68633,73413b847f63e02bc752b364f6d05ee9,013056cfe49763c6f66bda03396c5ee3,4,NaN,NaN,2018-03-04 00:00:00,2018-03-05 17:02:00
83224,d8e8c42271c8fb67b9dad95d98c8ff80,0176a6846bcb3b0d3aa3116a9a768597,5,NaN,NaN,2017-12-30 00:00:00,2018-01-02 10:54:47
89888,0c8e7347f1cdd2aede37371543e3d163,02355020fd0a40a0d56df9f6ff060413,3,NaN,UM DOS PRODUTOS (ENTREGA02) COMPRADOS NESTE PE...,2018-03-21 00:00:00,2018-03-22 01:32:08
55137,61fe4e7d1ae801bbe169eb67b86c6eda,029863af4b968de1e5d6a82782e662f5,4,NaN,NaN,2017-07-19 00:00:00,2017-07-20 12:06:11
...,...,...,...,...,...,...,...
80631,c509f8b367ee5227700c29fcc76a097a,fd95ae805c63c534f1a64589e102225e,5,NaN,"Recebi dentro do prazo estabelecido, produtos ...",2018-03-04 00:00:00,2018-03-06 10:10:08
42177,9da0796858da97acd8b67578388a3241,fe041ba1c9f54016432fa6ee91709dbc,5,NaN,"O cartucho está estourado (vazando), já contat...",2017-12-20 00:00:00,2017-12-20 22:03:18
94504,c56a88a404315a0d9e412c1472dda2c4,ff763b73e473d03c321bcd5a053316e8,5,NaN,NaN,2017-11-01 00:00:00,2017-11-01 19:55:52
41355,39de8ad3a1a494fc68cc2d5382f052f4,ff850ba359507b996e8b2fbb26df8d03,5,NaN,Envio rapido... Produto 100%,2017-08-16 00:00:00,2017-08-17 11:56:55
92230,870d856a4873d3a67252b0c51d79b950,ffaabba06c9d293a3c614e0515ddbabc,3,NaN,NaN,2017-12-20 00:00:00,2017-12-20 18:50:16

In [186]:
order_reviews_df[['review_id', 'order_id']].duplicated().any()

np.False_

In [133]:
order_reviews_df[order_reviews_df.duplicated(subset=['order_id', 'review_score'])].sort_values('order_id')

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
25612,89a02c45c340aeeb1354a24e7d4b2c1e,0035246a40f520710769010f752e7507,5,NaN,NaN,2017-08-29 00:00:00,2017-08-30 01:59:12
83224,d8e8c42271c8fb67b9dad95d98c8ff80,0176a6846bcb3b0d3aa3116a9a768597,5,NaN,NaN,2017-12-30 00:00:00,2018-01-02 10:54:47
35812,fa493ead9b093fb0fa6f7d4905b0ef3b,02e0b68852217f5715fb9cc885829454,4,NaN,Gostei e entregou rapidinho,2017-12-01 00:00:00,2017-12-03 21:57:31
42500,39b4603793c1c7f5f36d809b4a218664,02e723e8edb4a123d414f56cc9c4665e,5,NaN,Otimo,2017-09-01 00:00:00,2017-09-02 12:13:03
49625,5e1ee2e924a1dd10d80b99555383c0a7,03515a836bb855b03f7df9dee520a8fc,5,NaN,NaN,2018-01-31 00:00:00,2018-02-01 01:26:24
...,...,...,...,...,...,...,...
20401,c7528903f66f3c8400f50ae8525e77f6,f7c5c5ff5045e13c98901bbbf8e871d4,5,NaN,lindooo,2017-08-08 00:00:00,2017-08-16 18:16:08
80631,c509f8b367ee5227700c29fcc76a097a,fd95ae805c63c534f1a64589e102225e,5,NaN,"Recebi dentro do prazo estabelecido, produtos ...",2018-03-04 00:00:00,2018-03-06 10:10:08
42177,9da0796858da97acd8b67578388a3241,fe041ba1c9f54016432fa6ee91709dbc,5,NaN,"O cartucho está estourado (vazando), já contat...",2017-12-20 00:00:00,2017-12-20 22:03:18
41355,39de8ad3a1a494fc68cc2d5382f052f4,ff850ba359507b996e8b2fbb26df8d03,5,NaN,Envio rapido... Produto 100%,2017-08-16 00:00:00,2017-08-17 11:56:55
92230,870d856a4873d3a67252b0c51d79b950,ffaabba06c9d293a3c614e0515ddbabc,3,NaN,NaN,2017-12-20 00:00:00,2017-12-20 18:50:16

In [134]:
order_reviews_df[order_reviews_df.duplicated(subset=['order_id', 'review_score', 'review_creation_date'])].sort_values('order_id')

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
83224,d8e8c42271c8fb67b9dad95d98c8ff80,0176a6846bcb3b0d3aa3116a9a768597,5,NaN,NaN,2017-12-30 00:00:00,2018-01-02 10:54:47
56594,7a49d6129a979bbbb500cb14853d2714,056bfadd41b8600ad5ecfef2ac132188,4,NaN,NaN,2017-12-05 00:00:00,2017-12-09 13:53:55
97530,8e954c79dc2fc426d5f17035e9bb22dd,08c01d43e93f5c485f48758550d41eb9,1,NaN,Estou aguardando a entrega do produto.,2017-05-22 00:00:00,2017-05-22 19:19:11
52342,a804bcb9d26038f0af172d4d3e05aa98,0d404657f01231a876c9a25b6c91e329,5,NaN,NaN,2017-10-11 00:00:00,2017-10-15 17:24:24
26859,e8f7dfaf855afb7c0bbc3b55c25d31e3,0ed5043fe7d3f4f88353697330bbc020,5,NaN,NaN,2017-10-26 00:00:00,2017-10-26 22:23:26
...,...,...,...,...,...,...,...
89806,376c23240f8f0ed3279ce924b0d6a260,f494e4f6b6de7aeefe3af00acc8b3426,5,NaN,NaN,2017-06-24 00:00:00,2017-06-25 23:17:11
93109,dc4744d42039931c560913a239cbcb73,f707ff2a9514dce20b267136b60af042,4,Bom,NaN,2018-07-07 00:00:00,2018-07-07 22:33:21
20401,c7528903f66f3c8400f50ae8525e77f6,f7c5c5ff5045e13c98901bbbf8e871d4,5,NaN,lindooo,2017-08-08 00:00:00,2017-08-16 18:16:08
42177,9da0796858da97acd8b67578388a3241,fe041ba1c9f54016432fa6ee91709dbc,5,NaN,"O cartucho está estourado (vazando), já contat...",2017-12-20 00:00:00,2017-12-20 22:03:18
92230,870d856a4873d3a67252b0c51d79b950,ffaabba06c9d293a3c614e0515ddbabc,3,NaN,NaN,2017-12-20 00:00:00,2017-12-20 18:50:16

In [135]:
order_reviews_df[order_reviews_df.duplicated(subset=['order_id', 'review_score', 'review_creation_date', 'review_comment_title', 'review_comment_message'])].sort_values('order_id')

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
83224,d8e8c42271c8fb67b9dad95d98c8ff80,0176a6846bcb3b0d3aa3116a9a768597,5,NaN,NaN,2017-12-30 00:00:00,2018-01-02 10:54:47
56594,7a49d6129a979bbbb500cb14853d2714,056bfadd41b8600ad5ecfef2ac132188,4,NaN,NaN,2017-12-05 00:00:00,2017-12-09 13:53:55
52342,a804bcb9d26038f0af172d4d3e05aa98,0d404657f01231a876c9a25b6c91e329,5,NaN,NaN,2017-10-11 00:00:00,2017-10-15 17:24:24
26859,e8f7dfaf855afb7c0bbc3b55c25d31e3,0ed5043fe7d3f4f88353697330bbc020,5,NaN,NaN,2017-10-26 00:00:00,2017-10-26 22:23:26
42108,bebd0c23d7791cb07b4eb3e459e5920b,0ee24d5ae95ccf0552a2ef03dfadb924,4,NaN,NaN,2017-09-07 00:00:00,2017-09-08 01:17:50
...,...,...,...,...,...,...,...
94773,c9563b00af92aac9994bf58535dacf3a,dbf76ef1323584fa387945f83b324534,5,NaN,NaN,2017-10-11 00:00:00,2017-10-15 20:47:49
57736,101a60d1231091725c8cd2e98aa43630,dd73d93a25e576d8dae52c7c66b3becf,5,NaN,NaN,2017-10-04 00:00:00,2017-10-05 15:21:16
97308,68eb847f85bc01081e3ce1d881cb16ce,e00ed9d20c3479f9f0e9727ca9d60946,5,NaN,NaN,2017-12-22 00:00:00,2017-12-23 04:50:09
89806,376c23240f8f0ed3279ce924b0d6a260,f494e4f6b6de7aeefe3af00acc8b3426,5,NaN,NaN,2017-06-24 00:00:00,2017-06-25 23:17:11
92230,870d856a4873d3a67252b0c51d79b950,ffaabba06c9d293a3c614e0515ddbabc,3,NaN,NaN,2017-12-20 00:00:00,2017-12-20 18:50:16

In [136]:
order_reviews_df[order_reviews_df.duplicated(subset=['review_id','order_id', 'review_score', 'review_creation_date', 'review_comment_title', 'review_comment_message'])].sort_values('order_id')

Empty DataFrame
Columns: [review_id, order_id, review_score, review_comment_title, review_comment_message, review_creation_date, review_answer_timestamp]
Index: []

In [137]:
order_reviews_df.isna().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [138]:
order_reviews_df.dtypes

review_id                  object
order_id                   object
review_score                int64
review_comment_title       object
review_comment_message     object
review_creation_date       object
review_answer_timestamp    object
dtype: object

In [140]:
order_reviews_df['review_creation_date'] = pd.to_datetime(order_reviews_df['review_creation_date'])

In [141]:
order_reviews_df['review_creation_date'].min()

Timestamp('2016-10-02 00:00:00')

In [142]:
order_reviews_df['review_creation_date'].max()

Timestamp('2018-08-31 00:00:00')

In [143]:
order_reviews_df['review_answer_timestamp'] = pd.to_datetime(order_reviews_df['review_answer_timestamp'])

In [144]:
order_reviews_df['review_answer_timestamp'].min()

Timestamp('2016-10-07 18:32:28')

In [145]:
order_reviews_df['review_answer_timestamp'].max()

Timestamp('2018-10-29 12:27:35')

In [183]:
order_reviews_df['review_score'].unique()

array([4, 5, 1, 3, 2])

In [13]:
orders_df.shape

(99441, 8)

In [97]:
os.path.getsize('../data/raw/olist_orders_dataset.csv') / 1024

17241.126953125

In [69]:
orders_df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [70]:
orders_df[orders_df.duplicated(subset=['order_id'])]

Empty DataFrame
Columns: [order_id, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date]
Index: []

In [147]:
orders_df.isna().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [148]:
orders_df.dtypes

order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object

In [181]:
orders_df['order_status'].unique()

array(['delivered', 'invoiced', 'shipped', 'processing', 'unavailable',
       'canceled', 'created', 'approved'], dtype=object)

In [152]:
orders_time_columns = ['order_purchase_timestamp','order_approved_at','order_delivered_carrier_date','order_delivered_customer_date','order_estimated_delivery_date']

In [155]:
orders_df[orders_time_columns] = orders_df[orders_time_columns].apply(pd.to_datetime)

In [157]:
orders_df[orders_time_columns].dtypes

order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

In [163]:
orders_df[orders_time_columns].agg(['min','max']).T

                                              min                 max
order_purchase_timestamp      2016-09-04 21:15:19 2018-10-17 17:30:18
order_approved_at             2016-09-15 12:16:38 2018-09-03 17:40:06
order_delivered_carrier_date  2016-10-08 10:34:01 2018-09-11 19:48:28
order_delivered_customer_date 2016-10-11 13:46:32 2018-10-17 13:22:46
order_estimated_delivery_date 2016-09-30 00:00:00 2018-11-12 00:00:00

In [151]:
orders_df['order_purchase_timestamp'].max()

Timestamp('2018-10-17 17:30:18')

In [15]:
products_df.shape

(32951, 9)

In [98]:
os.path.getsize('../data/raw/olist_products_dataset.csv') / 1024

2323.677734375

In [71]:
products_df.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [78]:
products_df.isna().any()

product_id                    False
product_category_name          True
product_name_lenght            True
product_description_lenght     True
product_photos_qty             True
product_weight_g               True
product_length_cm              True
product_height_cm              True
product_width_cm               True
dtype: bool

In [77]:
products_df.isna().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [164]:
products_df.dtypes

product_id                     object
product_category_name          object
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

In [166]:
products_df[products_df.duplicated(subset=['product_id'])]

Empty DataFrame
Columns: [product_id, product_category_name, product_name_lenght, product_description_lenght, product_photos_qty, product_weight_g, product_length_cm, product_height_cm, product_width_cm]
Index: []

In [17]:
sellers_df.shape

(3095, 4)

In [99]:
os.path.getsize('../data/raw/olist_sellers_dataset.csv') / 1024

170.6083984375

In [169]:
sellers_df.isna().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [172]:
sellers_df.dtypes

seller_id                 object
seller_zip_code_prefix     int64
seller_city               object
seller_state              object
dtype: object

In [173]:
sellers_df.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [177]:
sellers_df[sellers_df.duplicated(subset=('seller_id'))]

Empty DataFrame
Columns: [seller_id, seller_zip_code_prefix, seller_city, seller_state]
Index: []

In [19]:
product_category_name_translation_df.shape

(71, 2)

In [100]:
os.path.getsize('../data/raw/product_category_name_translation.csv') / 1024

2.5517578125

In [68]:
product_category_name_translation_df.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [178]:
product_category_name_translation_df.isna().sum()

product_category_name            0
product_category_name_english    0
dtype: int64

In [179]:
product_category_name_translation_df.dtypes

product_category_name            object
product_category_name_english    object
dtype: object

In [83]:
products_df['product_category_name'].isin(product_category_name_translation_df['product_category_name']).all()

np.False_

In [84]:
products_df['product_category_name'].isin(product_category_name_translation_df['product_category_name']).sum()

np.int64(32328)

In [85]:
product_category_name_translation_df['product_category_name'].isin(products_df['product_category_name']).sum()

np.int64(71)

## orphan checks

In [223]:
# Order Items with no Orders
items_to_orders_check = order_items_df.merge(
    orders_df[['order_id']],
    on='order_id',
    how='left',
    indicator=True
)

items_to_orders_orphans = items_to_orders_check[
    items_to_orders_check['_merge'] == 'left_only'
]

print(len(items_to_orders_orphans))

0

In [224]:
# Order Items with no Products
items_to_products_check = order_items_df.merge(
    products_df[['product_id']],
    on='product_id',
    how='left',
    indicator=True
)

items_to_products_orphans = items_to_products_check[
    items_to_products_check['_merge'] == 'left_only'
]

print(len(items_to_products_orphans))

0

In [225]:
# Order_Items with no sellers
items_to_sellers_check = order_items_df.merge(
    sellers_df[['seller_id']],
    on='seller_id',
    how='left',
    indicator=True
)

items_to_sellers_orphans = items_to_sellers_check[
    items_to_sellers_check['_merge'] == 'left_only'
]

print(len(items_to_sellers_orphans))

0

In [226]:
# Payments with no orders
payments_to_orders_check = order_payments_df.merge(
    orders_df[['order_id']],
    on='order_id',
    how='left',
    indicator=True
)

payments_to_orders_orphans = payments_to_orders_check[
    payments_to_orders_check['_merge'] == 'left_only'
]

print(len(payments_to_orders_orphans))

0

In [227]:
# reviews with no orders
reviews_to_orders_check = order_reviews_df.merge(
    orders_df[['order_id']],
    on='order_id',
    how='left',
    indicator=True
)

reviews_to_orders_orphans = reviews_to_orders_check[
    reviews_to_orders_check['_merge'] == 'left_only'
]

print(len(reviews_to_orders_orphans))

0

In [228]:
# Orders with no Customers
orders_to_customers_check = orders_df.merge(
    customers_df[['customer_id']],
    on='customer_id',
    how='left',
    indicator=True
)

orders_to_customers_orphans = orders_to_customers_check[
    orders_to_customers_check['_merge'] == 'left_only'
]

print(len(orders_to_customers_orphans))

0

## I want to see that which key is beigh referenced in everywhere

In [22]:
# Orders with no Customers
orders_to_customers_check = orders_df.merge(
    customers_df[['customer_unique_id']],
    left_on='customer_id',
    right_on='customer_unique_id',
    how='left',
    indicator=True
)

orders_to_customers_orphans = orders_to_customers_check[
    orders_to_customers_check['_merge'] == 'left_only'
]

print(len(orders_to_customers_orphans))

99441

In [237]:
# Customers without matching zipcode
customer_zip_to_geo_check = customers_df.merge(
    geolocation_df[['geolocation_zip_code_prefix']],
    left_on='customer_zip_code_prefix',
    right_on='geolocation_zip_code_prefix',
    how='left',
    indicator=True
)

customer_zip_to_geo_orphans = customer_zip_to_geo_check[
    customer_zip_to_geo_check['_merge'] == 'left_only'
]

print(len(customer_zip_to_geo_orphans))

278

In [238]:
# Sellers without matching zipcode
seller_zip_to_geo_check = sellers_df.merge(
    geolocation_df[['geolocation_zip_code_prefix']],
    left_on='seller_zip_code_prefix',
    right_on='geolocation_zip_code_prefix',
    how='left',
    indicator=True
)

seller_zip_to_geo_orphans = seller_zip_to_geo_check[
    seller_zip_to_geo_check['_merge'] == 'left_only'
]

print(len(seller_zip_to_geo_orphans))

7

In [24]:
# orders with no items
orders_items_check = orders_df.merge(
    order_items_df[['order_id']],
    on='order_id',
    how='left',
    indicator=True
)

orders_no_items = orders_items_check[
    orders_items_check['_merge'] == 'left_only'
]

print(len(orders_no_items))

775

In [26]:
orders_no_items['order_status'].unique()

array(['unavailable', 'canceled', 'created', 'shipped', 'invoiced'],
      dtype=object)

In [27]:
# orders with no payments
orders_payments_check = orders_df.merge(
    order_payments_df[['order_id']].drop_duplicates(),
    on='order_id',
    how='left',
    indicator=True
)

orders_no_payments = orders_payments_check[
    orders_payments_check['_merge'] == 'left_only'
]

print(len(orders_no_payments))

1

In [28]:
orders_no_payments['order_status'].unique()

array(['delivered'], dtype=object)

In [241]:
# orders with no reviews
orders_reviews_check = orders_df.merge(
    order_reviews_df[['order_id']].drop_duplicates(),
    on='order_id',
    how='left',
    indicator=True
)

orders_no_reviews = orders_reviews_check[
    orders_reviews_check['_merge'] == 'left_only'
]

print(len(orders_no_reviews))

768

## cardinality checks

In [31]:
#Now the order items are sort in order_id and if no order it the count gets 0
per_order = (order_items_df.groupby('order_id').size()
             .reindex(orders_df['order_id'], fill_value=0))

print("min ", per_order.min())
print("max ", per_order.max())

min  0
max  21

In [36]:
per_order_payment = (order_payments_df.groupby('order_id').size()
    .reindex(orders_df['order_id'], fill_value=0))

print("min ", per_order_payment.min())
print("max ", per_order_payment.max())

min  0
max  29

In [38]:
per_review = (order_reviews_df.groupby('order_id').size()
                .reindex(orders_df['order_id'], fill_value=0))
print("min ", per_review.min())
print("max ", per_review.max())

min  0
max  3

In [40]:
per_customer = (orders_df.groupby('customer_id').size()
.reindex(customers_df['customer_id'], fill_value=0))
                
print("min ", per_customer.min())
print("max ", per_customer.max())

min  1
max  1

In [42]:
per_product = (order_items_df.groupby('product_id').size()
                .reindex(products_df['product_id'], fill_value=0))
print("min ", per_product.min())
print("max ", per_product.max())

min  1
max  527

In [43]:
per_seller = (order_items_df.groupby('seller_id').size()
                .reindex(sellers_df['seller_id'], fill_value=0))
print("min ", per_seller.min())
print("max ", per_seller.max())

min  1
max  2033